import { resizeImage } from '../../utils/image';
import { addArticleJsonLd } from '../../utils/seo/addArticleJsonLd';
import { getAutogeneratedPostOG } from '../../utils/social/og';
import request from 'graphql-request';
import Link from 'next/link';
import { Container } from '../../components/container';
import { AppProvider } from '../../components/contexts/appContext';
import { CoverImage } from '../../components/cover-image';
import { DateFormatter } from '../../components/date-formatter';
import { Footer } from '../../components/footer';
import { Layout } from '../../components/layout';
import { MarkdownToHtml } from '../../components/markdown-to-html';
import { Header } from '../../components/header';
import {
	PageByPublicationDocument,
	PostFullFragment,
	PublicationFragment,
	SinglePostByPublicationDocument,
	SlugPostsByPublicationDocument,
	StaticPageFragment,
} from '../../generated/graphql';
import { PostOrPageClient } from './post-or-page-client';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';


const Post = ({ publication, post }: { publication: PublicationFragment; post: PostFullFragment }) => {
	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';

	const tagsList = (post.tags ?? []).map((tag) => (
		<div key={tag.id}>
			<Link
				href={`/tags/${tag.slug}`}
				className="inline-block rounded-full bg-zinc-100 px-3 py-1 text-sm text-zinc-700 hover:bg-zinc-200 dark:bg-zinc-800 dark:text-zinc-300 dark:hover:bg-zinc-700"
			>
				#{tag.slug}
			</Link>
		</div>
	));

	const coverImageSrc = !!post.coverImage?.url
		? resizeImage(post.coverImage.url, {
				w: 1600,
				h: 840,
				c: 'thumb',
		  })
		: undefined;

	return (
		<>
			<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }}></style>
			<article className="mx-auto max-w-2xl">
				<header className="mb-8 space-y-6">
					<h1 className="text-4xl font-bold tracking-tight text-zinc-900 dark:text-white md:text-5xl">
						{post.title}
					</h1>
					<div className="flex flex-wrap items-center gap-x-3 text-sm text-zinc-500 dark:text-zinc-400">
						{/* <span className="font-medium text-zinc-700 dark:text-zinc-300">{post.author.name}</span> */}
						{/* <span>·</span> */}
						<DateFormatter dateString={post.publishedAt} />
						<span>·</span>
						<span>{post.readTimeInMinutes} min read</span>
					</div>
				</header>

				{!!coverImageSrc && (
					<div className="-mx-4 mb-8 overflow-hidden md:mx-0 md:rounded-lg">
						<CoverImage title={post.title} priority={true} src={coverImageSrc} />
					</div>
				)}

				<div className="prose prose-slate mx-auto dark:prose-invert">
					<MarkdownToHtml contentMarkdown={post.content.markdown} />
				</div>

				{(post.tags ?? []).length > 0 && (
					<div className="mt-8 flex flex-wrap gap-2">
						{tagsList}
					</div>
				)}
			</article>
		</>
	);
};

const Page = ({ page }: { page: StaticPageFragment }) => {
	return <MarkdownToHtml contentMarkdown={page.content.markdown} />;
};

export default async function PostOrPage({ params }: { params: Promise<{ slug: string }> }) {
	const endpoint = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST;
	const { slug } = await params;

	// Exclude common static file requests that shouldn't be processed as slugs
	const staticFileExtensions = ['.ico', '.png', '.jpg', '.jpeg', '.gif', '.svg', '.css', '.js', '.woff', '.woff2', '.ttf', '.eot'];
	const isStaticFile = staticFileExtensions.some(ext => slug.toLowerCase().endsWith(ext));

	if (isStaticFile) {
		notFound();
	}

	// Try to fetch as a post first
	const postData = await request(endpoint, SinglePostByPublicationDocument, { host, slug });

	if (postData.publication?.post) {
		const post = postData.publication.post;
		const publication = postData.publication;

		return (
			<AppProvider publication={publication} post={post} page={null}>
				<Layout publication={publication}>
					<Container className="mx-auto flex max-w-5xl flex-col items-stretch gap-10 px-5 py-10">
						<Header />
						<article className="flex flex-col items-start gap-10 pb-10">
							<Post publication={publication} post={post} />
							<PostOrPageClient post={post} />
						</article>
						<Footer publication={publication} />
					</Container>
				</Layout>
			</AppProvider>
		);
	}

	// Try to fetch as a page
	const pageData = await request(endpoint, PageByPublicationDocument, { host, slug });

	if (pageData.publication?.staticPage) {
		const page = pageData.publication.staticPage;
		const publication = pageData.publication;

		return (
			<AppProvider publication={publication} post={null} page={page}>
				<Layout publication={publication}>
					<Container className="mx-auto flex max-w-5xl flex-col items-stretch gap-10 px-5 py-10">
						<Header />
						<article className="flex flex-col items-start gap-10 pb-10">
							<Page page={page} />
							<PostOrPageClient post={null} />
						</article>
						<Footer publication={publication} />
					</Container>
				</Layout>
			</AppProvider>
		);
	}

	// If neither post nor page found, return 404
	notFound();
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
	const endpoint = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST;
	const { slug } = await params;

	// Exclude common static file requests that shouldn't be processed as slugs
	const staticFileExtensions = ['.ico', '.png', '.jpg', '.jpeg', '.gif', '.svg', '.css', '.js', '.woff', '.woff2', '.ttf', '.eot'];
	const isStaticFile = staticFileExtensions.some(ext => slug.toLowerCase().endsWith(ext));

	if (isStaticFile) {
		return {
			title: 'Not Found',
			description: 'The page you are looking for does not exist.',
		};
	}

	const postData = await request(endpoint, SinglePostByPublicationDocument, { host, slug });

	if (postData.publication?.post) {
		const post = postData.publication.post;
		const publication = postData.publication;

		return {
			title: post.seo?.title || post.title,
			description: post.seo?.description || post.subtitle || post.brief,
			openGraph: {
				title: post.seo?.title || post.title,
				description: post.seo?.description || post.subtitle || post.brief,
				images: [
					post.ogMetaData?.image ||
					post.coverImage?.url ||
					getAutogeneratedPostOG(post, publication)
				],
				type: 'article',
				publishedTime: post.publishedAt,
				authors: [post.author.name],
			},
			twitter: {
				card: 'summary_large_image',
				title: post.seo?.title || post.title,
				description: post.seo?.description || post.subtitle || post.brief,
				images: [
					post.ogMetaData?.image ||
					post.coverImage?.url ||
					getAutogeneratedPostOG(post, publication)
				],
			},
			other: {
				'application/ld+json': JSON.stringify(addArticleJsonLd(publication, post)),
			},
		};
	}

	const pageData = await request(endpoint, PageByPublicationDocument, { host, slug });

	if (pageData.publication?.staticPage) {
		const page = pageData.publication.staticPage;

		return {
			title: page.title,
			description: page.title,
		};
	}

	return {
		title: 'Not Found',
		description: 'The page you are looking for does not exist.',
	};
}

export async function generateStaticParams() {
	const data = await request(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SlugPostsByPublicationDocument,
		{
			first: 10,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const postSlugs = (data.publication?.posts.edges ?? []).map((edge) => edge.node.slug);

	return postSlugs.map((slug) => ({
		slug: slug,
	}));
}
